name: GitHub Actions Linux Testing

on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean assemble --stacktrace
        
  test:
    needs: build
    strategy:
      matrix:
        tests: [ProtobufJavaPluginTest, ProtobufKotlinDslCopySpecTest, ProtobufKotlinDslPluginTest, ProtobufAndroidPluginTest, ProtobufAndroidPluginKotlinTest, AndroidProjectDetectionTest, IDESupportTest]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test --tests ${{ matrix.tests }} --stacktrace

  codenarc:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: codenarcMain codenarcTest --continue
      - name: echo codenarcMain reports
        if: failure()
        run: test -f build/reports/codenarc/main.txt && cat build/reports/codenarc/main.txt
      - name: echo codenarcTest reports
        if: failure()
        run: test -f build/reports/codenarc/test.txt && cat build/reports/codenarc/test.txt
